# Generated by Django 5.2.7 on 2025-10-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
